# TCL File Generated by Component Editor 23.1
# Sat Jan 31 10:50:54 GMT 2026
# DO NOT MODIFY


# 
# fp_add_sub "fp_add_sub" v1.0
#  2026.01.31.10:50:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fp_add_sub
# 
set_module_property DESCRIPTION ""
set_module_property NAME fp_add_sub
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fp_add_sub
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fp_add_sub
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fp_add_sub.v VERILOG PATH ip/custom_fp_add_sub/fp_add_sub.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave_1
# 
add_interface nios_custom_instruction_slave_1 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_1 clockCycle 4
set_interface_property nios_custom_instruction_slave_1 operands 2
set_interface_property nios_custom_instruction_slave_1 ENABLED true
set_interface_property nios_custom_instruction_slave_1 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_1 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_1 areset reset Input 1
add_interface_port nios_custom_instruction_slave_1 en clk_en Input 1
add_interface_port nios_custom_instruction_slave_1 a dataa Input 32
add_interface_port nios_custom_instruction_slave_1 b datab Input 32
add_interface_port nios_custom_instruction_slave_1 q result Output 32
add_interface_port nios_custom_instruction_slave_1 opSel n Input 1
add_interface_port nios_custom_instruction_slave_1 clk clk Input 1

